### [D1107_work_김현우]

In [446]:
# 1) 넘파이 임포트

import numpy as np

In [447]:
# 2) ndarray

data = [1, 2, 3]
np.array(data)

array([1, 2, 3])

In [448]:
# 3) arange

np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [449]:
# 4) arange

arr = np.arange(1, 10) * 3
print(arr)

[ 3  6  9 12 15 18 21 24 27]


In [450]:
# 5) arange

np.arange(2, 1000, 2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208,
       210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234,
       236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260,
       262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286,
       288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312,
       314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338,
       340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 36

In [451]:
# 6) 실수 range

arr = np.arange(0, 1, 0.1)
arr

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [452]:
# 7) reshape

data = [0, 1, 2, 3, 4, 5]

arr = np.array(data)
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [453]:
# 8) reshape

rr = np.array([
    [0, 1, 2],
    [3, 4, 5]
])

# rr.reshape(6)
rr = rr.flatten()

In [454]:
# 9) reshape

arr = np.arange(3)
arr.reshape(3, 1)

array([[0],
       [1],
       [2]])

In [455]:
# 10) 에러의 원인
# np.arange(6).reshape(2, 4)

# 결과값이 총 6개인데 reshape(2, 4)를 하면 8개의 원소를 넣어야 함

In [456]:
# 11) 2차원 배열

arr = np.arange(6)
arr = arr.reshape(2, 3)

In [457]:
# 12) ones
data1 = [1] * 20
data1 = np.array(data)
print(data1)

data2 = np.ones(20, dtype=int)
print(data2)

[0 1 2 3 4 5]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [458]:
# 13) ones

data = np.ones(20, dtype=int)
data.reshape(4, 5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [459]:
# 14) ones

data = [255] * 100
data = np.array(data).reshape(10, 10)
print(data)

[[255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]]


In [460]:
# 15) zeros

data = np.zeros(12).reshape(3, 4)
# data = np.zeros((3, 4))
data

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [461]:
# 16) dtype

data = np.arange(1, 4)
data

data2 = [1, 2, 3]
arr = np.array(data2, dtype=np.int32)
arr

array([1, 2, 3], dtype=int32)

In [462]:
# 17) dtype

arr = np.array([1, 2, 3])
print(arr.dtype)

int64


In [463]:
# 18) dtype

arr = np.array(['1', '2', '3'])
print(arr.dtype)

<U1


In [464]:
# 19) dtype

arr = np.array([1, 2, 3])
arr.astype(np.int16)

array([1, 2, 3], dtype=int16)

In [465]:
# 20) 데이터 타입

# a = np.array([255, 300, 128], dtype=np.uint8)

# uint8은 unsigned int로 0 ~ 2^8-1 인데 300은 이를 초과해서 오류가 뜸

In [466]:
# 21) astype

arr = np.array([1.1, 2.1, 3.1])
arr.astype(np.int32)

array([1, 2, 3], dtype=int32)

In [467]:
# 22) linspace

data = np.linspace(0, 10, 20)
data

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [468]:
# 23) 로우 인덱싱

rr = np.arange(9).reshape(3, 3)
rr

print(rr[2])
# print(rr[-1])

[6 7 8]


In [469]:
# 24) 컬럼 인덱싱

arr = np.arange(9).reshape(3, 3)


print(arr[:, 1])

[1 4 7]


In [470]:
# 25) 데이터 인덱싱

arr = np.arange(25).reshape(5, 5)
arr

print(arr[3, 2])

17


In [471]:
# 26) 슬라이싱

arr = np.arange(5)
arr

print(arr[1::2])

[1 3]


In [472]:
# 27) 슬라이싱

arr = np.arange(25).reshape(5, 5)
print(arr)

print(arr[1][1:])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[6 7 8 9]


In [473]:
# 28) 슬라이싱

arr = np.arange(25).reshape(5, 5)
arr

print(arr[:, :2])

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]
 [20 21]]


In [474]:
# 29) 슬라이싱

arr = np.arange(25).reshape(5, 5)
arr

data = arr[1:3, 1:3]
print(data)

[[ 6  7]
 [11 12]]


In [475]:
# 30) 슬라이싱

arr = np.arange(25).reshape(5, 5)
print(arr)

data = arr[[0, 4]][:, [0, 3]]
print(data)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  3]
 [20 23]]


In [476]:
# 31) ndarray 곱셈

data = [1, 2, 3]

ndarray = np.array(data) * 10
print(ndarray)

[10 20 30]


In [477]:
# 32) ndarray 제곱

data = [1, 2, 3]

ndarray = np.array(data) ** 2
print(ndarray)

[1 4 9]


In [478]:
# 33) ndarray 루트

data = [1, 2, 3]

ndarray = np.array(data)
print(np.sqrt(ndarray))

[1.         1.41421356 1.73205081]


In [479]:
# 34) ndarray 컬럼 평균

score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])

print(score.mean(axis=0))

[12. 18.]


In [480]:
# 35) ndarray 로우 표준편차

score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])

print(score.std(axis=1))

[5. 1.]


In [481]:
# 36) 행렬곱

a = np.arange(   4).reshape(2,2)
a

b = np.arange(1, 5).reshape(2,2)
b

print(a @ b)
# print(np.matmul(a, b))
# print(np.dot(a, b))

[[ 3  4]
 [11 16]]


In [482]:
# 37) 전치행렬

arr = np.arange(9).reshape(3, 3)
print(arr)

print(np.transpose(arr))
print(arr.transpose())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [483]:
# 38) 짝수 배열

arr = np.arange(10)
print(arr)

print(arr[0::2])

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [484]:
# 39) 홀수 배열

arr = np.arange(10)
print(arr)

print(arr[1::2])

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [485]:
# 40) 여러 조건

arr = np.arange(10)
print(arr)

# print(arr[4:8])
print(arr[(arr>3) & (arr<7)])

[0 1 2 3 4 5 6 7 8 9]
[4 5 6]


In [486]:
# 41) 조건에 맞는 원소값 출력

arr = np.array([-1, 2, -3, 4])

print(arr[arr<0])

[-1 -3]


In [487]:
# 42) 조건에 맞는 원소값 변경

arr = np.array([-1, 2, -3, 4])

arr[arr<0] = 0
print(arr)

[0 2 0 4]


In [488]:
# 43) 조건에 맞는 원소값 변경

arr = np.array([-1, 2, -3, 4])

print(abs(arr))

# cond = arr < 0
# arr[cond] = -arr[cond]|

[1 2 3 4]


In [493]:
# 44) 조건에 맞는 원소값 변경

arr = np.array([-1, 2, -3, 4])

# cond1 = arr < 0
# cond2 = arr >= 0

# arr[cond1] = arr[cond1] - 10
# arr[cond2] = arr[cond2] + 10

# print(arr)

print(np.where(arr>=0, arr + 10, arr - 10))

[-11  12 -13  14]


In [502]:
# 45) shuffle

arr = [1, 2, 3, 4, 5]

arr = np.array(arr)
print(arr)

np.random.shuffle(arr)
print(arr)

[1 2 3 4 5]
[3 5 1 2 4]


In [508]:
# 46) argmin

arr = np.array([1, 2, 3, 4, 5])

min_index = arr.argmin()
print(min_index)

0


In [511]:
# 47) argmax

arr = np.array([1, 2, 3, 4, 5])
max_index = arr.argmax()
print(max_index)

4


In [517]:
# 48) 정렬

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr.sort()
arr[::-1].sort() # 내림차순
print(arr)

[8 7 6 5 4 3 2 1]


In [523]:
# 49) numpy.vstack

arr1 = np.array([1, 2])
arr2 = np.array([3, 4])

result = np.vstack((arr1, arr2))
print(result)

[[1 2]
 [3 4]]


In [526]:
# 50) flatten

arr = np.array([ [1, 2], [3, 4] ])

arr = arr.flatten()
print(arr)

[1 2 3 4]
