### [ndarray 객체 생성]

In [85]:
import numpy as np

In [86]:
# 함수: numpy.ndarray()
# -------------------------------------------
# numpy ndarray 객체 생성 + 데이터 타입 설정
nparray01 = np.array([1, 2, 3, 4, 5], dtype=np.int8)
# -------------------------------------------
# ndarray 속성
print('type(nparray01)          =', type(nparray01))
print('nparray01.shape)         =', nparray01.shape)        # 원소 개수
print('nparray01.size)          =', nparray01.size)         # 원소 1개 저장 바이트 수 
print('nparray01.itemsize)      =', nparray01.itemsize)     # 원소 1개 저장 바이트 수
print('nparray01.dtype)         =', nparray01.dtype)
print(nparray01)

type(nparray01)          = <class 'numpy.ndarray'>
nparray01.shape)         = (5,)
nparray01.size)          = 5
nparray01.itemsize)      = 1
nparray01.dtype)         = int8
[1 2 3 4 5]


In [87]:
# 함수: numpy.ndarray 객체 생성: 다른 타입의 데이터가 섞인 경우 자동 형변환
# ----------------------------------------------------------------------------------
nparray01 = np.array([1, 2., 3, 4, 5])  # 실수 데이터(2.) 때문에 전체를 실수로 저장
# ----------------------------------------------------------------------------------
# ndarray 속성
print('type(nparray01)      =', type(nparray01))
print('nparray01.shape)     =', nparray01.shape)      # 원소 개수
print('nparray01.size)      =', nparray01.size)       # 원소 1개 저장 바이트 수 
print('nparray01.itemsize)  =', nparray01.itemsize)   # 원소 1개 저장 바이트 수
print('nparray01.dtype)     =', nparray01.dtype)      # 원소들의 타입
print(nparray01)

type(nparray01)      = <class 'numpy.ndarray'>
nparray01.shape)     = (5,)
nparray01.size)      = 5
nparray01.itemsize)  = 8
nparray01.dtype)     = float64
[1. 2. 3. 4. 5.]


In [88]:
# 함수: numpy.ndarray 객체 생성: 다른 타입의 데이터가 섞인 경우 자동 형변환
# ----------------------------------------------------------------------------------
nparray01 = np.array([1, '2', 3, 4, 5])  # 데이터('2') 때문에 전체를 유니코드로 저장
# ----------------------------------------------------------------------------------
# ndarray 속성
print('type(nparray01)      =', type(nparray01))
print('nparray01.shape)     =', nparray01.shape)      # 원소 개수
print('nparray01.size)      =', nparray01.size)       # 원소 1개 저장 바이트 수 
print('nparray01.itemsize)  =', nparray01.itemsize)   # 원소 1개 저장 바이트 수
print('nparray01.dtype)     =', nparray01.dtype)      # 원소들의 타입
print(nparray01)

type(nparray01)      = <class 'numpy.ndarray'>
nparray01.shape)     = (5,)
nparray01.size)      = 5
nparray01.itemsize)  = 84
nparray01.dtype)     = <U21
['1' '2' '3' '4' '5']


In [89]:
# 함수: numpy.ndarray 객체 생성: 3행 2열
# ----------------------------------------------------------------------------------
nparray01 = np.array([[11, 22], [33, 44], [55, 66]]) 
# ----------------------------------------------------------------------------------
# ndarray 속성
print('type(nparray01)      =', type(nparray01))
print('nparray01.shape)     =', nparray01.shape)      # 원소 개수
print('nparray01.size)      =', nparray01.size)       # 원소 1개 저장 바이트 수 
print('nparray01.itemsize)  =', nparray01.itemsize)   # 원소 1개 저장 바이트 수
print('nparray01.dtype)     =', nparray01.dtype)      # 원소들의 타입
print(nparray01)

type(nparray01)      = <class 'numpy.ndarray'>
nparray01.shape)     = (3, 2)
nparray01.size)      = 6
nparray01.itemsize)  = 8
nparray01.dtype)     = int64
[[11 22]
 [33 44]
 [55 66]]


In [90]:
# 함수: numpy.ndarray 객체 생성: 3행 2열
# ----------------------------------------------------------------------------------
nparray01 = np.array([[[[8]]]])  # 대괄호[] 수에 따라 차원 구분
# ----------------------------------------------------------------------------------
# ndarray 속성
print('type(nparray01)      =', type(nparray01))
print('nparray01.shape)     =', nparray01.shape)      # 원소 개수
print('nparray01.size)      =', nparray01.size)       # 원소 1개 저장 바이트 수 
print('nparray01.itemsize)  =', nparray01.itemsize)   # 원소 1개 저장 바이트 수
print('nparray01.dtype)     =', nparray01.dtype)      # 원소들의 타입
print(nparray01)

type(nparray01)      = <class 'numpy.ndarray'>
nparray01.shape)     = (1, 1, 1, 1)
nparray01.size)      = 1
nparray01.itemsize)  = 8
nparray01.dtype)     = int64
[[[[8]]]]
