### [ndarray 객체 생성]

In [100]:
import numpy as np

In [101]:
# -------------------------------------------
# 함수: numpy.zeros(shape, 0) : [기본] float
# -------------------------------------------
# numpy ndarray 객체 생성 + 데이터 타입 설정
nparray01 = np.zeros((5,))

# -------------------------------------------
# ndarray 속성
print('type(nparray01)          =', type(nparray01))
print('nparray01.shape)         =', nparray01.shape)        # 원소 개수
print('nparray01.size)          =', nparray01.size)         # 원소 1개 저장 바이트 수 
print('nparray01.itemsize)      =', nparray01.itemsize)     # 원소 1개 저장 바이트 수
print('nparray01.dtype)         =', nparray01.dtype)        # 원소들의 타입
print(nparray01)

type(nparray01)          = <class 'numpy.ndarray'>
nparray01.shape)         = (5,)
nparray01.size)          = 5
nparray01.itemsize)      = 8
nparray01.dtype)         = float64
[0. 0. 0. 0. 0.]


In [102]:
# -------------------------------------------
# 함수: numpy.zeros(shape, 1) : [기본] float
# -------------------------------------------
# numpy ndarray 객체 생성 + 데이터 타입 설정
nparray01 = np.ones((2, 3, 1, 2))

# -------------------------------------------
# ndarray 속성
print('type(nparray01)          =', type(nparray01))
print('nparray01.shape)         =', nparray01.shape)        # 원소 개수
print('nparray01.size)          =', nparray01.size)         # 원소 1개 저장 바이트 수 
print('nparray01.itemsize)      =', nparray01.itemsize)     # 원소 1개 저장 바이트 수
print('nparray01.dtype)         =', nparray01.dtype)        # 원소들의 타입
print(nparray01)

type(nparray01)          = <class 'numpy.ndarray'>
nparray01.shape)         = (2, 3, 1, 2)
nparray01.size)          = 12
nparray01.itemsize)      = 8
nparray01.dtype)         = float64
[[[[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]]


 [[[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]]]


In [103]:
# -------------------------------------------
# 함수: numpy.full(shape, data) : [기본] float
# -------------------------------------------
# numpy ndarray 객체 생성 + 데이터 타입 설정
nparray01 = np.full((2, 4), 7)

# -------------------------------------------
# ndarray 속성
print('type(nparray01)          =', type(nparray01))
print('nparray01.shape)         =', nparray01.shape)        # 원소 개수
print('nparray01.size)          =', nparray01.size)         # 원소 1개 저장 바이트 수 
print('nparray01.itemsize)      =', nparray01.itemsize)     # 원소 1개 저장 바이트 수
print('nparray01.dtype)         =', nparray01.dtype)        # 원소들의 타입
print(nparray01)

type(nparray01)          = <class 'numpy.ndarray'>
nparray01.shape)         = (2, 4)
nparray01.size)          = 8
nparray01.itemsize)      = 8
nparray01.dtype)         = int64
[[7 7 7 7]
 [7 7 7 7]]


In [104]:
# -------------------------------------------------------------------------------
# 함수: numpy.zeros_like(ndarray 객체) : [기본] float
# -------------------------------------------------------------------------------
# numpy ndarray 객체 생성
a = np.array([11, 22])
nparray01 = np.zeros_like(a)
nparray02 = np.ones_like(a)

# -------------------------------------------------------------------------------
# ndarray 속성
print('type(nparray01)          =', type(nparray01))
print('nparray01.shape)         =', nparray01.shape)        # 원소 개수
print('nparray01.size)          =', nparray01.size)         # 원소 1개 저장 바이트 수 
print('nparray01.itemsize)      =', nparray01.itemsize)     # 원소 1개 저장 바이트 수
print('nparray01.dtype)         =', nparray01.dtype)        # 원소들의 타입
print(nparray01, '\n')

print('type(nparray02)          =', type(nparray02))
print('nparray02.shape)         =', nparray02.shape)        # 원소 개수
print('nparray02.size)          =', nparray02.size)         # 원소 1개 저장 바이트 수 
print('nparray02.itemsize)      =', nparray02.itemsize)     # 원소 1개 저장 바이트 수
print('nparray02.dtype)         =', nparray02.dtype)        # 원소들의 타입
print(nparray02, '\n')

type(nparray01)          = <class 'numpy.ndarray'>
nparray01.shape)         = (2,)
nparray01.size)          = 2
nparray01.itemsize)      = 8
nparray01.dtype)         = int64
[0 0] 

type(nparray02)          = <class 'numpy.ndarray'>
nparray02.shape)         = (2,)
nparray02.size)          = 2
nparray02.itemsize)      = 8
nparray02.dtype)         = int64
[1 1] 



In [105]:
# -------------------------------------------------------------------------------
# 함수: numpy.arrange([start, ] stop[, step]]) : 1D ndarray
#      [기본값] start = 0, step = 1
# -------------------------------------------------------------------------------
# numpy ndarray 객체 생성
nparray01 = np.arange(5)

# -------------------------------------------------------------------------------
# ndarray 속성
print('type(nparray01)          =', type(nparray01))
print('nparray01.shape)         =', nparray01.shape)        # 원소 개수
print('nparray01.size)          =', nparray01.size)         # 원소 1개 저장 바이트 수 
print('nparray01.itemsize)      =', nparray01.itemsize)     # 원소 1개 저장 바이트 수
print('nparray01.dtype)         =', nparray01.dtype)        # 원소들의 타입
print(nparray01, '\n')

type(nparray01)          = <class 'numpy.ndarray'>
nparray01.shape)         = (5,)
nparray01.size)          = 5
nparray01.itemsize)      = 8
nparray01.dtype)         = int64
[0 1 2 3 4] 



In [106]:
# -------------------------------------------------------------------------------
# 함수: numpy.arrange([start, ] stop[, step]]) : 1D ndarray
#      [기본값] start = 0, step = 1
# -------------------------------------------------------------------------------
# numpy ndarray 객체 생성
nparray01 = np.arange(2, 10, 3)

# -------------------------------------------------------------------------------
# ndarray 속성
print('type(nparray01)          =', type(nparray01))
print('nparray01.shape)         =', nparray01.shape)        # 원소 개수
print('nparray01.size)          =', nparray01.size)         # 원소 1 저장 바이트 수 
print('nparray01.itemsize)      =', nparray01.itemsize)     # 원소 1개 저장 바이트 수
print('nparray01.dtype)         =', nparray01.dtype)        # 원소들의 타입
print(nparray01, '\n')

type(nparray01)          = <class 'numpy.ndarray'>
nparray01.shape)         = (3,)
nparray01.size)          = 3
nparray01.itemsize)      = 8
nparray01.dtype)         = int64
[2 5 8] 



In [107]:
# -------------------------------------------------------------------------------
# 함수: numpy.linspace(start, stop, num=50,
#                      endpoint=True, retstep=False)
#      1D ndarray float
#      [기본값] start <= ~ <= stop 사이 num개 숫자 생성
# -------------------------------------------------------------------------------
# numpy ndarray 객체 생성
nparray01 = np.linspace(0, 3, num=5)                       # 0 <= ~ <= 3 범위에서 10개 숫자 생성
nparray01, step = np.linspace(0, 3, num=5, retstep=True)   # 숫자 사이 간격값 반환
# -------------------------------------------------------------------------------
# 숫자 사이 간격값
print('step                     =', step)

# ndarray 속성
print('type(nparray01)          =', type(nparray01))
print('nparray01.shape)         =', nparray01.shape)        # 원소 개수
print('nparray01.size)          =', nparray01.size)         # 원소 1 저장 바이트 수 
print('nparray01.itemsize)      =', nparray01.itemsize)     # 원소 1개 저장 바이트 수
print('nparray01.dtype)         =', nparray01.dtype)        # 원소들의 타입
print(nparray01, '\n')

step                     = 0.75
type(nparray01)          = <class 'numpy.ndarray'>
nparray01.shape)         = (5,)
nparray01.size)          = 5
nparray01.itemsize)      = 8
nparray01.dtype)         = float64
[0.   0.75 1.5  2.25 3.  ] 



In [108]:
# -------------------------------------------------------------------------------
# 함수: numpy.empty(shape, dtype)
#      1D ndarray float
#      초기화 되지 않은/쓰레기 값의 배열 생성
# -------------------------------------------------------------------------------
# numpy ndarray 객체 생성
nparray01 = np.empty((3, 4))
# -------------------------------------------------------------------------------
# ndarray 속성
print('nparray01.shape)         =', nparray01.shape)        # 원소 개수
print('nparray01.size)          =', nparray01.size)         # 원소 1 저장 바이트 수 
print('nparray01.dtype)         =', nparray01.dtype)        # 원소들의 타입
print(nparray01, '\n')

nparray01.shape)         = (3, 4)
nparray01.size)          = 12
nparray01.dtype)         = float64
[[4.9e-324 9.9e-324 1.5e-323 2.0e-323]
 [2.5e-323 3.0e-323 3.5e-323 4.0e-323]
 [4.4e-323 4.9e-323 5.4e-323 5.9e-323]] 



In [109]:
# -------------------------------------------------------------------------------
# (1) 1차원 인덱싱/슬라이싱
# -------------------------------------------------------------------------------
# 데이터 준비
b = np.array([10, 20, 30, 40, 50])
#             0 , 1 , 2 , 3 , 4
# -------------------------------------------------------------------------------
# ndarray 속성
print('b[0])      =', b[0])        # 10 (첫 원소)
print('b[-1])     =', b[-1])       # 50 (뒤에서 첫 원소)
print('b[1:4])    =', b[1:4])      # 슬라이스 [20, 30, 40]
print('b[:3])     =', b[:3])       # 처음~2 인덱스까지
print('b[::2])    =', b[::2])      # step = 2
print('b[::-1])   =', b[::-1])     # 역순

b[0])      = 10
b[-1])     = 50
b[1:4])    = [20 30 40]
b[:3])     = [10 20 30]
b[::2])    = [10 30 50]
b[::-1])   = [50 40 30 20 10]


In [110]:
# -------------------------------------------------------------------------------
# 3) Fancy 인덱싱(정수 배열/리스트로 선택)
#    - 불연속/불규칙적인 임의의 데이터 추출
#    - 형식 : 변수명[ [행번호 리스트] ]
#            변수명[:, [열번호 리스트] ]
# -------------------------------------------------------------------------------
# 데이터 준비
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# -------------------------------------------------------------------------------
# 추출 변수
rows, cols = [0, 2], [1, 0]

# -------------------------------------------------------------------------------
# 여러 개의 행 추출
print(a)
print('-----------------------')
print('a[rows] =>\n', a[rows])               # a[ [0, 2]]
print()

# 여러 개의 컬럼 추출
print(a)
print('-----------------------')
print('a[cols] =>\n', a[:, cols])            # a[:, [1, 0]]
print()

# -------------------------------------------------------------------------------
# 같은 위치 쌍 선택
print(a)
print('-----------------------')
print('a[rows, cols] =>\n', a[rows, cols])  # a[ [0, 2], [1, 0]],  0번 위치: (0,1) / 1번 위치: (2,0)
print()

# -------------------------------------------------------------------------------
# 행/열 조합의 격자 선택: np.ix_(rows, cols)
print(a)
print('-----------------------')
print('a[np.ix(rows, cols)] =>\n', a[np.ix_(rows, cols)])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-----------------------
a[rows] =>
 [[ 1  2  3  4]
 [ 9 10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-----------------------
a[cols] =>
 [[ 2  1]
 [ 6  5]
 [10  9]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-----------------------
a[rows, cols] =>
 [2 9]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-----------------------
a[np.ix(rows, cols)] =>
 [[ 2  1]
 [10  9]]


In [112]:
#-------------------------------------------------------------------------------
# 4) 불리언 마스크(조건 인덱싱)
#    - & : 그리고, 모든 조건 True
#    - | : 또는, 1개 이상 True
#    - ~ : 반대
#    - 비교연산자: >, >=, <, <=, ==, !=
# -------------------------------------------------------------------------------
# 데이터 준비
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# => 짝수 위치 True
mask = (a % 2 == 0)
print("mask = \n, mask", '\n')

# => 조건 만족 원소 1차원으로 반환
print("a[mask] = ", a[mask], '\n')

# => 마스크로 값 변경(브로드캐스팅)
a2 = a.copy()
a2[a2 % 3 == 0] = -1
print('a2 (3의 배수만 -1): \n', a2, '\n')

# -------------------------------------------------------------------------------
# numpy함수들: 조건에 따른 결과 반환
# -------------------------------------------------------------------------------
# => 조건에 따라 치환 : np.where(조건, True일 때, False일 때)
replaced = np.where(a % 2 == 0, a, 0)
print('np.where 짝수 유지, 홀수 0:\n', replaced, '\n')

# => 조건 만족하는 (행, 열) 얻기: np.argwhere(조건)
idxs = np.argwhere(a >= 8)
print("a >= 8의 (행, 열) 인덱스: \n", idxs, '\n')

# => 인덱스 얻기: np.nonzero()
#               축마다(행따로, 열따로) 0 아닌 요소의 인덱스를 1차원 배열
#               tuple(행 array, 열 array)
idxs = np.nonzero(a)
print('0아닌 요소의 인덱스: \n', idxs, '\n')

# -------------------------------------------------------------------------------
# 5) view vs copy (슬라이스는 view, fancy는 copy)
#    - view : 원본과 메모리 공유
#    - copy : 원본의 복사본 다른 메모리
# -------------------------------------------------------------------------------
# => view
base = np.arange(10)    # 0 <= ~ < 10, 간격 1
s1   = base[2:6]
s1[0]= 999

# => 메모리 공유로 함께 적용
print("슬라이스 수정 후 base =", base)

# => copy : # fancy -> copy (별도 배열)
base2 = np.arange(10)
fz = base2[[2, 3, 4, 5]]    # 인덱스를 리스트에 담은 것 => 팬시 인덱싱
fz[0] = 777
print("fancy 수정 후 base2 =", base2, "(변화 없음) \n")
print("슬라이스 수정 후 fz =", fz)

mask = 
, mask 

a[mask] =  [ 2  4  6  8 10 12] 

a2 (3의 배수만 -1): 
 [[ 1  2 -1  4]
 [ 5 -1  7  8]
 [-1 10 11 -1]] 

np.where 짝수 유지, 홀수 0:
 [[ 0  2  0  4]
 [ 0  6  0  8]
 [ 0 10  0 12]] 

a >= 8의 (행, 열) 인덱스: 
 [[1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]] 

0아닌 요소의 인덱스: 
 (array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3])) 

슬라이스 수정 후 base = [  0   1 999   3   4   5   6   7   8   9]
fancy 수정 후 base2 = [0 1 2 3 4 5 6 7 8 9] (변화 없음) 

슬라이스 수정 후 fz = [777   3   4   5]
