### [ndarray 원소 다루기]
- 인덱싱 : 
    * 변수명[인덱스] / 변수명[행인덱스][열인덱스]
- 슬라이싱: 
    * 변수명[시작인덱스 : 끝인덱스 : 간격]
    * 변수명[행시작인덱스 : 행끝인덱스 : 간격, 열시작인덱스: 열끝인덱스:간격]
    * 범위 : 시작인덱스 <= ~ < 끝인덱스

In [125]:
import numpy as np

In [126]:
# -------------------------------------------
# 함수: numpy.zeros(shape, 0) : [기본] float
# -------------------------------------------
# numpy ndarray 객체 생성 + 데이터 타입 설정
nparray01 = np.zeros((5,))

# -------------------------------------------
# ndarray 속성
print('type(nparray01)          =', type(nparray01))
print('nparray01.shape)         =', nparray01.shape)        # 원소 개수
print('nparray01.size)          =', nparray01.size)         # 원소 1개 저장 바이트 수 
print('nparray01.itemsize)      =', nparray01.itemsize)     # 원소 1개 저장 바이트 수
print('nparray01.dtype)         =', nparray01.dtype)        # 원소들의 타입
print(nparray01)

type(nparray01)          = <class 'numpy.ndarray'>
nparray01.shape)         = (5,)
nparray01.size)          = 5
nparray01.itemsize)      = 8
nparray01.dtype)         = float64
[0. 0. 0. 0. 0.]


In [127]:
# -------------------------------------------
# 함수: numpy.zeros(shape, 1) : [기본] float
# -------------------------------------------
# numpy ndarray 객체 생성 + 데이터 타입 설정
nparray01 = np.ones((2, 3, 1, 2))

# -------------------------------------------
# ndarray 속성
print('type(nparray01)          =', type(nparray01))
print('nparray01.shape)         =', nparray01.shape)        # 원소 개수
print('nparray01.size)          =', nparray01.size)         # 원소 1개 저장 바이트 수 
print('nparray01.itemsize)      =', nparray01.itemsize)     # 원소 1개 저장 바이트 수
print('nparray01.dtype)         =', nparray01.dtype)        # 원소들의 타입
print(nparray01)

type(nparray01)          = <class 'numpy.ndarray'>
nparray01.shape)         = (2, 3, 1, 2)
nparray01.size)          = 12
nparray01.itemsize)      = 8
nparray01.dtype)         = float64
[[[[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]]


 [[[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]]]


In [128]:
# -------------------------------------------
# 함수: numpy.full(shape, data) : [기본] float
# -------------------------------------------
# numpy ndarray 객체 생성 + 데이터 타입 설정
nparray01 = np.full((2, 4), 7)

# -------------------------------------------
# ndarray 속성
print('type(nparray01)          =', type(nparray01))
print('nparray01.shape)         =', nparray01.shape)        # 원소 개수
print('nparray01.size)          =', nparray01.size)         # 원소 1개 저장 바이트 수 
print('nparray01.itemsize)      =', nparray01.itemsize)     # 원소 1개 저장 바이트 수
print('nparray01.dtype)         =', nparray01.dtype)        # 원소들의 타입
print(nparray01)

type(nparray01)          = <class 'numpy.ndarray'>
nparray01.shape)         = (2, 4)
nparray01.size)          = 8
nparray01.itemsize)      = 8
nparray01.dtype)         = int64
[[7 7 7 7]
 [7 7 7 7]]


In [129]:
# -------------------------------------------------------------------------------
# 함수: numpy.zeros_like(ndarray 객체) : [기본] float
# -------------------------------------------------------------------------------
# numpy ndarray 객체 생성
a = np.array([11, 22])
nparray01 = np.zeros_like(a)
nparray02 = np.ones_like(a)

# -------------------------------------------------------------------------------
# ndarray 속성
print('type(nparray01)          =', type(nparray01))
print('nparray01.shape)         =', nparray01.shape)        # 원소 개수
print('nparray01.size)          =', nparray01.size)         # 원소 1개 저장 바이트 수 
print('nparray01.itemsize)      =', nparray01.itemsize)     # 원소 1개 저장 바이트 수
print('nparray01.dtype)         =', nparray01.dtype)        # 원소들의 타입
print(nparray01, '\n')

print('type(nparray02)          =', type(nparray02))
print('nparray02.shape)         =', nparray02.shape)        # 원소 개수
print('nparray02.size)          =', nparray02.size)         # 원소 1개 저장 바이트 수 
print('nparray02.itemsize)      =', nparray02.itemsize)     # 원소 1개 저장 바이트 수
print('nparray02.dtype)         =', nparray02.dtype)        # 원소들의 타입
print(nparray02, '\n')

type(nparray01)          = <class 'numpy.ndarray'>
nparray01.shape)         = (2,)
nparray01.size)          = 2
nparray01.itemsize)      = 8
nparray01.dtype)         = int64
[0 0] 

type(nparray02)          = <class 'numpy.ndarray'>
nparray02.shape)         = (2,)
nparray02.size)          = 2
nparray02.itemsize)      = 8
nparray02.dtype)         = int64
[1 1] 



In [130]:
# -------------------------------------------------------------------------------
# 함수: numpy.arrange([start, ] stop[, step]]) : 1D ndarray
#      [기본값] start = 0, step = 1
# -------------------------------------------------------------------------------
# numpy ndarray 객체 생성
nparray01 = np.arange(5)

# -------------------------------------------------------------------------------
# ndarray 속성
print('type(nparray01)          =', type(nparray01))
print('nparray01.shape)         =', nparray01.shape)        # 원소 개수
print('nparray01.size)          =', nparray01.size)         # 원소 1개 저장 바이트 수 
print('nparray01.itemsize)      =', nparray01.itemsize)     # 원소 1개 저장 바이트 수
print('nparray01.dtype)         =', nparray01.dtype)        # 원소들의 타입
print(nparray01, '\n')

type(nparray01)          = <class 'numpy.ndarray'>
nparray01.shape)         = (5,)
nparray01.size)          = 5
nparray01.itemsize)      = 8
nparray01.dtype)         = int64
[0 1 2 3 4] 



In [131]:
# -------------------------------------------------------------------------------
# 함수: numpy.arrange([start, ] stop[, step]]) : 1D ndarray
#      [기본값] start = 0, step = 1
# -------------------------------------------------------------------------------
# numpy ndarray 객체 생성
nparray01 = np.arange(2, 10, 3)

# -------------------------------------------------------------------------------
# ndarray 속성
print('type(nparray01)          =', type(nparray01))
print('nparray01.shape)         =', nparray01.shape)        # 원소 개수
print('nparray01.size)          =', nparray01.size)         # 원소 1 저장 바이트 수 
print('nparray01.itemsize)      =', nparray01.itemsize)     # 원소 1개 저장 바이트 수
print('nparray01.dtype)         =', nparray01.dtype)        # 원소들의 타입
print(nparray01, '\n')

type(nparray01)          = <class 'numpy.ndarray'>
nparray01.shape)         = (3,)
nparray01.size)          = 3
nparray01.itemsize)      = 8
nparray01.dtype)         = int64
[2 5 8] 



In [132]:
# -------------------------------------------------------------------------------
# 함수: numpy.linspace(start, stop, num=50,
#                      endpoint=True, retstep=False)
#      1D ndarray float
#      [기본값] start <= ~ <= stop 사이 num개 숫자 생성
# -------------------------------------------------------------------------------
# numpy ndarray 객체 생성
nparray01 = np.linspace(0, 3, num=5)                       # 0 <= ~ <= 3 범위에서 10개 숫자 생성
nparray01, step = np.linspace(0, 3, num=5, retstep=True)   # 숫자 사이 간격값 반환
# -------------------------------------------------------------------------------
# 숫자 사이 간격값
print('step                     =', step)

# ndarray 속성
print('type(nparray01)          =', type(nparray01))
print('nparray01.shape)         =', nparray01.shape)        # 원소 개수
print('nparray01.size)          =', nparray01.size)         # 원소 1 저장 바이트 수 
print('nparray01.itemsize)      =', nparray01.itemsize)     # 원소 1개 저장 바이트 수
print('nparray01.dtype)         =', nparray01.dtype)        # 원소들의 타입
print(nparray01, '\n')

step                     = 0.75
type(nparray01)          = <class 'numpy.ndarray'>
nparray01.shape)         = (5,)
nparray01.size)          = 5
nparray01.itemsize)      = 8
nparray01.dtype)         = float64
[0.   0.75 1.5  2.25 3.  ] 



In [133]:
# -------------------------------------------------------------------------------
# 함수: numpy.empty(shape, dtype)
#      1D ndarray float
#      초기화 되지 않은/쓰레기 값의 배열 생성
# -------------------------------------------------------------------------------
# numpy ndarray 객체 생성
nparray01 = np.empty((3, 4))
# -------------------------------------------------------------------------------
# ndarray 속성
print('nparray01.shape)         =', nparray01.shape)        # 원소 개수
print('nparray01.size)          =', nparray01.size)         # 원소 1 저장 바이트 수 
print('nparray01.dtype)         =', nparray01.dtype)        # 원소들의 타입
print(nparray01, '\n')

nparray01.shape)         = (3, 4)
nparray01.size)          = 12
nparray01.dtype)         = float64
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

