D1218_WORK_김현우

In [499]:
import cv2
img = cv2.imread('../Data/Image/blackpink.jpg')
type(img)

numpy.ndarray

In [500]:
img.ndim
img.shape
img.size
img.dtype
img.itemsize

1

In [501]:
import numpy as np
a = np.array([1, 2, 3, 4])
a.dtype
a.shape

b = np.array([[1,2,3,4], [5,6,7,8]])
b
b.shape

c = np.array([1, 2, 3.14, 4])
c
c.dtype

dtype('float64')

In [502]:
a = np.uint8([1, 2, 3, 4])
a

array([1, 2, 3, 4], dtype=uint8)

In [503]:
a = np.empty((2, 3))
a
a.dtype

dtype('float64')

In [504]:
a.fill(255)
a

array([[255., 255., 255.],
       [255., 255., 255.]])

In [505]:
b = np.zeros((2, 3))
b
b.dtype

dtype('float64')

In [506]:
d = np.ones((2, 3))
d

array([[1., 1., 1.],
       [1., 1., 1.]])

In [507]:
e = np.full((2, 3, 4), 255, dtype=np.uint8)
e

array([[[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]],

       [[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]]], dtype=uint8)

In [508]:
img = cv2.imread('../Data/Image/girl.jpg')
img
img.shape

(293, 406, 3)

In [509]:
a = np.empty_like(img)
a.shape

(293, 406, 3)

In [510]:
b = np.zeros_like(img)
b

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], shape=(293, 406, 3), dtype=uint8)

In [511]:
c = np.ones_like(img)
c

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        ...,
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        ...,
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        ...,
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       ...,

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        ...,
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        ...,
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        ...,
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], shape=(293, 406, 3), dtype=uint8)

In [512]:
d = np.full_like(img, 255)
d

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [513]:
a = np.arange(5)
a
a.dtype
a.shape

(5,)

In [514]:
b = np.arange(5.0)
b
b.dtype

dtype('float64')

In [515]:
c = np.arange(3, 9, 2)
c

array([3, 5, 7])

In [516]:
np.random.rand()
np.random.randn()

a = np.random.rand(2, 3)
a

b = np.random.randn(2, 3)
b

array([[ 0.31116139,  0.82753501, -0.25134338],
       [ 0.45592573, -0.96479832,  0.4285717 ]])

In [517]:
a = np.arange(5)
a
a.dtype

b = a.astype('float32')
b

array([0., 1., 2., 3., 4.], dtype=float32)

In [518]:
a.dtype

c = a.astype(np.float64)
c
c.dtype

dtype('float64')

In [ ]:
a.dtype

d = np.uint8(a)
d

array([0, 1, 2, 3, 4], dtype=uint8)

array([0, 1, 2, 3, 4], dtype=uint8)

In [ ]:
a = np.arange(6)
a 

b = a.reshape(2, 3)
b

c = np.reshape(a, (2, 3))
c

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
d = np.arange(100).reshape(2, -1)
d
d.shape

(2, 50)

In [ ]:
e = np.arange(100).reshape(-1, 5)
e
e.shape

(20, 5)

In [ ]:
f = np.zeros((2, 3))
f
f.reshape((6,))
f.reshape(-1)
np.ravel(f)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
g = np.arange(10).reshape(2, -1)
g
g.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [ ]:
mylist = list(range(10))
mylist

for i in range(len(mylist)):
    mylist[i] = mylist[i]+1

mylist

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
a = np.arange(10)
a 
a + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a = np.arange(5)
a
a+5
a-2
a+2
a*2
a/2
a**2


array([ 0,  1,  4,  9, 16])

In [ ]:
b = np.arange(6).reshape(2, -1)
b
b*2

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [ ]:
a
a > 2

array([False, False, False,  True,  True])

In [ ]:
a = np.arange(10, 60, 10)
b = np.arange(1, 6)
b
a+b
a-b
a*b
a/b
a**b

array([       10,       400,     27000,   2560000, 312500000])

In [ ]:
# a = np.ones((2, 3))
# a
# b = np.ones((3, 2))
# b
# a+b

In [ ]:
# a
# c = np.arange(3)
# c
# a+c

In [ ]:
# d = np.arange(2)
# a + d

In [ ]:
a

d = np.arange(2).reshape(2, 1)
d
a+d

array([[10, 20, 30, 40, 50],
       [11, 21, 31, 41, 51]])

In [ ]:
a = np.arange(10)
a

a[5]
b = np.arange(12).reshape(3,4)
b
b[1]
b[1, 2]

np.int64(6)

In [ ]:
a
a[5] = 9
a
b
b[0] = 0
b
b[1, 2] = 99
b

array([[ 0,  0,  0,  0],
       [ 4,  5, 99,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a = np.arange(10)
a
a[2:5]
a[5:]
a[:]

b = np.arange(12).reshape(3, 4)
b

b[0:2, 1]
b

b[0:2, 1:3]
print(b)

b[2, :]

b[:, 1]

b[0:2, 1:3] = 0
b

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  0,  0,  3],
       [ 4,  0,  0,  7],
       [ 8,  9, 10, 11]])

In [ ]:
print(b)

bb = b[0:2, 1:3]
print(bb)

bb[0] = 99
print(b)

[[ 0  0  0  3]
 [ 4  0  0  7]
 [ 8  9 10 11]]
[[0 0]
 [0 0]]
[[ 0 99 99  3]
 [ 4  0  0  7]
 [ 8  9 10 11]]


In [ ]:
a = np.arange(5)
a

a[[1, 3]]

a[[True, False, True, False, True]]

array([0, 2, 4])

In [ ]:
a = np.arange(10)
a

b = a > 5
b

a[b]
a[a>5]
a[a>5] = 1
a

array([0, 1, 2, 3, 4, 5, 1, 1, 1, 1])

In [ ]:
b = np.arange(12).reshape(3, 4)
b
b[[0, 2]]

b[[0,2], [2,3]]

array([ 2, 11])

In [ ]:
a = np.arange(4).reshape(2, 2)
a

b = np.arange(10, 14).reshape(2, 2)
b

np.vstack((a, b))

np.hstack((a, b))

np.concatenate((a, b))

np.concatenate((a, b), 1)

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

In [ ]:
a = np.arange(12).reshape(4, 3)
b = np.arange(10, 130, 10).reshape(4, 3)
a
b

c = np.stack((a, b), 0)
c.shape
c

d = np.stack((a, b), 1)
d.shape
d

e = np.stack((a, b), 2)
e
e.shape

ee = np.stack((a, b), -1)
ee.shape

(4, 3, 2)

In [ ]:
a = np.arange(12)
a

np.hsplit(a, 3)

np.hsplit(a, [3, 6])

np.hsplit(a, [3, 6, 9])

np.split(a, 3, 0)

np.split(a, [3,6,9], 0)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [ ]:
b = np.arange(12).reshape(4,3)
b

np.vsplit(b, 2)

np.split(b, 2, 0)

np.hsplit(b, [1])

np.split(b, [1], 1)

[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]])]

In [ ]:
a = np.arange(10, 20)
a

np.where(a > 15)

np.where(a > 15, 1, 0)

a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
a

np.where(a > 15, 99, a)

np.where(a>15, a, 0)

a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
b = np.arange(12).reshape(3, 4)
b

coords = np.where(b>6)
coords

np.stack((coords[0], coords[1]), -1)

array([[1, 3],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3]])

In [ ]:
z = np.array([0,1,2,0,1,2])
np.nonzero(z)

zz = np.array([[0, 1, 2], [1,2,0], [2,0,1]])
zz

coords = np.nonzero(zz)
coords

np.stack((coords[0], coords[1]), -1)

array([[0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [2, 0],
       [2, 2]])

In [ ]:
a
np.nonzero(a>15)

np.where(a>15)

b

np.nonzero(b>6)

np.where(b>6)

(array([1, 2, 2, 2, 2]), array([3, 0, 1, 2, 3]))

In [ ]:
t = np.array([True, True, True])
np.all(t)

t[1] = False
t

np.all(t)

np.False_

In [ ]:
tt = np.array([[True, True], [False, True], [True, True]])
tt

np.all(tt, 0)
np.all(tt, 1)


array([ True, False,  True])

In [ ]:
a = np.arange(10)
b = np.arange(10)
a
b

a==b

np.all(a==b)

b[5] = -1
a

b

np.all(a==b)

b[5] = -1
a
b
np.all(a==b)

np.where(a==b)

np.where(a!=b)

(array([5]),)

In [ ]:
a = np.arange(12).reshape(3, 4)
a

np.sum(a)
np.sum(a, 0)

np.sum(a ,1)

array([ 6, 22, 38])

In [ ]:
np.mean(a)

np.mean(a, 0)

np.mean(a, 1)

np.amin(a)

np.amin(a, 0)

np.amin(a, 1)

np.amax(a)

np.amax(a, 0)

np.amax(a, 1)

array([ 3,  7, 11])

In [ ]:
np.amin is np.min

np.max is np.amax

False