#### [Numpy - Array 생성]

In [29]:
# 모듈 로딩
import numpy as np
import pandas as pd

In [30]:
# =======================================================
# 빈 array 객체 생성
# =======================================================
# 원하는 형태의 메모리 공간 할당, 초기화는 안돼있음(empty)
a1 = np.empty((3, 4))
a2 = np.empty(2)       
print(a1)
print()
print(a2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[5.74307717e-298 1.28104596e-142]


In [31]:
# 초기화 -> 값 넣기
a1.fill(0)  # 0으로 초기화
print(a1, '\n')

a3 = np.zeros((3,4))
print(a3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# =======================================================
# 0으로 채운 array 객체 생성
# =======================================================
# -> float64(기본)
a1 = np.ones((2, 3))
print(a1.dtype, a1, sep='\n')

# ======
print()
# ======

# -> int8 
a1 = np.ones((2, 3), dtype=np.int8) # 음수 없으면 uint
print(a1.dtype, a1, sep='\n')

# ======
print()
# ======

# -> bool
a1 = np.ones((2, 3), dtype=np.bool)
print(a1.dtype, a1, sep='\n')

float64
[[1. 1. 1.]
 [1. 1. 1.]]

int8
[[1 1 1]
 [1 1 1]]

bool
[[ True  True  True]
 [ True  True  True]]
