#### [Numpy - Array 생성]

[1] 모듈 로딩 및 이미지 로딩 <hr>

In [17]:
# =======================================================
# 모듈 로딩
# =======================================================
import numpy as np      # 이미지 데이터 저장 관련 모듈
import cv2              # opencv 패키지

In [18]:
# =======================================================
# image => 로딩: ndarray 데이터
# =======================================================
# 이미지 파일
IMG_FILE = './Data/Image/blackpink.jpg'

# 이미지 데이터 로딩 : cv2.imread(이미지파일경로)
imgNP = cv2.imread(IMG_FILE)

print(f"이미지 로우 데이터 정보 => {imgNP.shape}, {imgNP.ndim}D차원")

이미지 로우 데이터 정보 => (704, 1199, 3), 3D차원


[2] 이미지와 동일 형태/타입의 ndarray 객체 생성 <hr>

In [ ]:
array_ = np.empty_like(imgNP)
print(f"이미지와 동일 형태/타입 객체 => {array_.shape}, {array_.ndim}D차원")
print(array_)

이미지와 동일 형태/타입 객체 => (704, 1199, 3), 3D차원
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
