#### [Numpy - 자료형 변환/형변환/캐스팅]
- 묵시적 형변환 : 작은 데이터 타입 => 큰 데이터 타입 : 시스템에서 자동 진행
- 명시적 형변환 : 큰 데이터 타입 => 작은 데이터 타입 : 개발자가 진행, 데이터 손실 발생
    - 일반적으로 형변환 의미가 명시적 형변환

[1] 모듈 로딩 및 이미지 로딩 <hr>

In [2]:
# =======================================================
# 모듈 로딩
# =======================================================
import numpy as np      # 이미지 데이터 저장 관련 모듈
import cv2              # opencv 패키지

In [3]:
# =======================================================
# image => 로딩: ndarray 데이터
# =======================================================
# 이미지 파일
IMG_FILE = './Data/Image/blackpink.jpg'

# 이미지 데이터 로딩 : cv2.imread(이미지파일경로)
imgNP = cv2.imread(IMG_FILE)

print(f"이미지 로우 데이터 정보 => {imgNP.shape}, {imgNP.ndim}D차원")

이미지 로우 데이터 정보 => (704, 1199, 3), 3D차원


[2] 이미지와 동일 형태/타입의 ndarray 객체 생성 <hr>

In [4]:
array_ = np.empty_like(imgNP)
print(f"이미지와 동일 형태/타입 객체 => {array_.shape}, {array_.ndim}D차원")
print(array_)

이미지와 동일 형태/타입 객체 => (704, 1199, 3), 3D차원
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


[3] 임의의 데이터 생성 및 형변환 <hr>

In [7]:
# 임의의 데이터 ndarray 객체 생성
a = np.arange(11, 21, 3)
print(a.shape, a.dtype, a, sep='\n')

(4,)
int64
[11 14 17 20]


In [9]:
# 방법 1) astype() 메서드 활용
a.astype('float16')

array([11., 14., 17., 20.], dtype=float16)

In [13]:
# 방법 2) np.타입이름XX(ndarray) 함수 활용
np.uint8(a)

print('변경 후', a, a.dtype)

변경 후 [11 14 17 20] int64
