#### [Numpy - ndarray 형태 변경]
- 1차원 => N차원 => 1차원 : 원소 개수 변경 안됨!
- 1차원 <=> N차원 : 
    - np.reshape()함수, ndarray.reshape()메서드
    - np.resize()함수, ndarray.resize()메서드 **<==예외**
- N차원 => 1차원 : 
    - np.flatten()함수, ndarray.flatten()메서드, 
    - np.ravel()함수, ndarray.ravel()메서드


[1] 모듈 로딩 및 이미지 로딩 <hr>

In [212]:
# =======================================================
# 모듈 로딩
# =======================================================
import numpy as np      # 이미지 데이터 저장 관련 모듈
import cv2              # opencv 패키지

In [213]:
# 지정된 시작값부터 끝값 미만까지 step 간격으로 정수나 실수 배열을 생성합니다.
n1 = np.arange(1, 10, 3)
print(n1, '\n')

# 로그 스케일로 시작 지수부터 끝 지수까지 num개의 값을 생성합니다(기본 base=10)
n2 = np.logspace(1, 10, 2)
print(n2, '\n')

# 시작값부터 끝값까지(포함) num개의 균등 간격 값을 생성합니다.
n3 = np.linspace(1, 10, 4)
print(n3, '\n')

# 0~1 사이 균등 분포 난수를 생성합니다(모든 차원에 대해)
n4 = np.random.rand()
print(n4, '\n')

[1 4 7] 

[1.e+01 1.e+10] 

[ 1.  4.  7. 10.] 

0.1114443418003036 



In [214]:
# 임의의 데이터 ndaray
a = np.arange(11, 23)
print(a.shape, a.dtype, a, sep='\n')

(12,)
int64
[11 12 13 14 15 16 17 18 19 20 21 22]


In [215]:
# ==========================================================================
# 다양한 형태(shape) 변경
# ==========================================================================
# 10 (12,) => 2D : (1, 12), (2, 5), (3, 4), (4, 3), (6, 2), (12, 1)

d2 = a.reshape((3, 4))
print("(3, 4) 변경 후", d2.shape)

d2 = a.reshape((3, -1))
print("(3, -1) 변경 후", d2.shape)

d2 = a.reshape((-1, 1))
print("(-1, 1) 변경 후", d2.shape)

(3, 4) 변경 후 (3, 4)
(3, -1) 변경 후 (3, 4)
(-1, 1) 변경 후 (12, 1)


In [216]:
# 1D (12,) => 3D : (1, 1, 12), (2, 1, 6), (6, 2, 1)
d2 = a.reshape((1, 1, 12))
print('(1, 1, 12) 변경 후', d2.shape, d2.ndim)

d2 = a.reshape((-1, 2, 1))
print('(-1, 2, 1) 변경 후', d2.shape, d2.ndim)

d2 = a.reshape((2, -1, 2))
print('(2, -1, 2) 변경 후', d2.shape, d2.ndim)

d2 = np.reshape(a, (2, -1, 2))
print('(2, -1, 2) 변경 후', d2.shape, d2.ndim)

d2 = np.reshape(a, (-1,))
print('(-1,) 변경 후', d2.shape, d2.ndim)

(1, 1, 12) 변경 후 (1, 1, 12) 3
(-1, 2, 1) 변경 후 (6, 2, 1) 3
(2, -1, 2) 변경 후 (2, 3, 2) 3
(2, -1, 2) 변경 후 (2, 3, 2) 3
(-1,) 변경 후 (12,) 1


In [217]:
# # 원소 개수 변경 : 12개 --------> ValueError 발생
# d2 = a.reshape((3, 3, 2))       # 3 * 3 * 2 = 18개 원소
# print('(3, 3, 2) 변경 후', d2.shape, d2.ndim)

# d2 = np.reshape(a, (2, -1, 2))
# print('(2, -1, 2) 변경 후', d2.shape, d2.ndim)

In [218]:
# ==========================================================================
# 다양한 형태(shape) 변경 / 원소 개수 변경 가능
# ==========================================================================
# 10 (12,) => 2D : (1, 12), (2, 5), (3, 4), (4, 3), (6, 2), (12, 1)
# 원본 바로 적용
a.resize((3, 4))
print("(3, 4) 변경 후", a, sep='\n')

# # -1 사용 불가X
# a.resize((-1, 6))
# print("(-1, 6) 변경 후", a, sep='\n')

# 함수 사용
d3 = np.resize(a, (1, 2, 6))
print("(1, 2, 6) 변경 후", d3, sep='\n')

# 함수 사용 -> 원소 개수 변경
d4 = np.resize(d3, (1, 6))
print("(1, 6) 변경 후", d4, sep='\n')

d4 = np.resize(d3, (1, 8))
print("(1, 8) 변경 후", d4, sep='\n')


(3, 4) 변경 후
[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
(1, 2, 6) 변경 후
[[[11 12 13 14 15 16]
  [17 18 19 20 21 22]]]
(1, 6) 변경 후
[[11 12 13 14 15 16]]
(1, 8) 변경 후
[[11 12 13 14 15 16 17 18]]


In [219]:
# ==========================================================================
# 다양한 형태(shape) 변경 / 원소 개수 변경 가능
# ==========================================================================
# 10 (12,) => 2D : (1, 12), (2, 5), (3, 4), (4, 3), (6, 2), (12, 1)
# 원본 바로 적용
a.resize((3, 4))
print("(3, 4) 변경 후", a, sep='\n')

# # -1 사용 불가X
# a.resize((-1, 6))
# print("(-1, 6) 변경 후", a, sep='\n')

# 함수 사용
d3 = np.resize(a, (1, 2, 6))
print("(1, 2, 6) 변경 후", d3, sep='\n')

# 함수 사용 -> 원소 개수 변경
d3 = np.resize(d3, (1, 6))
print("(1, 6) 변경 후", d3, sep='\n')

d3 = np.resize(d3, (1, 8))
print("(1, 8) 변경 후", d3, sep='\n')

# 메서드 적용 -> 원소 개수 변경
a = np.arange(11, 23)
print(a.shape, a.dtype, a, sep='\n')

a.resize((2, 8), refcheck=False)
print(a.shape, a.dtype, a, sep='\n')

(3, 4) 변경 후
[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
(1, 2, 6) 변경 후
[[[11 12 13 14 15 16]
  [17 18 19 20 21 22]]]
(1, 6) 변경 후
[[11 12 13 14 15 16]]
(1, 8) 변경 후
[[11 12 13 14 15 16 11 12]]
(12,)
int64
[11 12 13 14 15 16 17 18 19 20 21 22]
(2, 8)
int64
[[11 12 13 14 15 16 17 18]
 [19 20 21 22  0  0  0  0]]


In [220]:
# ==========================================================================
# 다양한 형태(shape) 변경 : N차원 --------> 1차원
# ==========================================================================
# 방법1) reshape(), resize()
# -> reshape() : 원본 적용 X, -1 사용 가능

a = np.array([[11, 12], [13, 14], [15, 16]])
print(a.shape, a, sep='\n')

a1 = a.reshape(-1)
print(a1.shape, a1, sep='\n')

# 방법 1) reshape(), resize()
# -> resize() : 원본 적용 0, -1 사용 불가능
a.reshape(6)
print(a.shape, a, sep='\n')

(3, 2)
[[11 12]
 [13 14]
 [15 16]]
(6,)
[11 12 13 14 15 16]
(3, 2)
[[11 12]
 [13 14]
 [15 16]]


In [221]:
# 방법 2) flatten()
# -> flatten() : 복사본 생성 후 1차원 변환. 속도가 상대적으로 느림
a = np.array([[[11, 12], [13, 14], [15, 16]]])
print("원본 => ", a.shape, a, sep='\n')

print()

a1 = a.flatten()
print("1차원 변형 :", a1)

a[0][0][0] = 77
print("원본 a => ", a, sep='\n')
print("변형 a1 => ", a1)

원본 => 
(1, 3, 2)
[[[11 12]
  [13 14]
  [15 16]]]

1차원 변형 : [11 12 13 14 15 16]
원본 a => 
[[[77 12]
  [13 14]
  [15 16]]]
변형 a1 =>  [11 12 13 14 15 16]


In [222]:
# 방법 3) ravel()
# -> ravel() : 원본 공유해서 1차원 변환.
a = np.array([[[11, 12], [13, 14], [15, 16]]])
print("원본 => ", a.shape, a, sep='\n')

print()

a1 = a.ravel()
print("1차원 변형 :", a1)

a[0][0][0] = 77
print("원본 a => ", a, sep='\n')
print("변형 a1 => ", a1)

원본 => 
(1, 3, 2)
[[[11 12]
  [13 14]
  [15 16]]]

1차원 변형 : [11 12 13 14 15 16]
원본 a => 
[[[77 12]
  [13 14]
  [15 16]]]
변형 a1 =>  [77 12 13 14 15 16]
