#### [Numpy - ndarray 축 axis 변경]
- ndarray의 축 확인 -> shape 속성
    - 예: shape(3, 2, 1) => 0번축 3, 1번축 2, 2번축 1
    - 예: shape(1, 1, 2 ,3) => 0번축 1, 1번축 1, 2번축 2, 3번축 3
    - 예: shape(6,) => 1D

[1] 모듈 로딩 및 이미지 로딩 <hr>

In [17]:
# =======================================================
# 모듈 로딩
# =======================================================
import numpy as np      # 이미지 데이터 저장 관련 모듈
import cv2              # opencv 패키지

In [18]:
# 임의의 데이터 ndarray 객체 생성
a = np.ones((2, 2, 3))
print(a.shape, a.dtype, a, sep='\n')


(2, 2, 3)
float64
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [19]:
# =========================================================
# 축 변경 : T & transpose()
# =========================================================
# ndarray의 속성 T
a = a.T
print('a.T 적용 후 => ', a, sep='\n')

# ndarray의 메서드 transpose((축 번호 튜플))
# 현재 (2, 2, 3) => (2, 0, 1)
at = np.transpose(a, (2, 0, 1))   # 함수 (ndarray객체, (축 번호 튜플))
print('a.transpose() 적용 후 => ', at, sep='\n')


a.T 적용 후 => 
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
a.transpose() 적용 후 => 
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
