#### 【 연속확률분포 (Continuous Distribution) + 추론검정 】

[4] t-분포 (Student’s t Distribution) <hr>
- 표본 크기가 작고(보통 n < 30), 모분산을 모를 때 **평균의 추론에 사용하는 분포**
- 예시
    * 남학생과 여학생의 평균 점수 차이가 유의미한가?
    * 우리 반 평균 키가 165cm인가?
    * A반과 B반의 평균 점수가 다를까?
    * 교육 전·후 평균 점수가 달라졌나?”
    * 이 집단의 평균은 95% 신뢰수준에서 (72점, 81점) 사이이다.
- 정의 : 
    * $$ T = \frac{\bar{X} - \mu_0}{S / \sqrt{n}}  $$
    * X bar: 표본평균, μ0 : 가설의 평균(예: 0, 70 등)
    * S : 표본표준편차, n : 표본 크기,  𝑇 ∼ 𝑡𝑛−1
- 결과값 : 표본평균이 평균(μ₀)에서 몇 표준오차만큼 떨어져 있는지 나타냄
    * |T|가 크다 → 표본평균이 μ₀랑 꽤 다르다. → 평균 차이가 크다고 주장 가능
    * |T|가 작다 → 표본평균이 μ₀ 근처에 있다. → 차이가 없다고 보기 쉬움

- 특징
    * 평균 0
    * 꼬리가 두꺼움(표본이 적을 때 불확실성이 더 크기 때문)
    * 자유도(df) 증가 → 정규분포에 점점 가까워짐

In [ ]:
#  모듈 로딩
import numpy as np
from scipy import stats

# 1) 작은 표본 데이터 (예: 수업 후 시험 점수 12명)
scores = np.array([72, 68, 75, 80, 77, 69, 73, 71, 74, 78, 70, 76])

# 2) 표본 통계량 계산
n     = len(scores)                 # 표본 크기
x_bar = scores.mean()               # 표본 평균
s     = scores.std(ddof=1)          # 표본 표준편차 (ddof=1 잊지 말기!)

print(f"표본 크기 n = {n}")
print(f"표본 평균 x̄ = {x_bar:.2f}")
print(f"표본 표준편차 s = {s:.2f}")

In [ ]:
# 3) t-분포의 임계값 구하기 (95% 신뢰구간 → 양쪽 2.5%씩)
alpha, df = 0.05, n-1
t_crit = stats.t.ppf(1 - alpha/2, df)   # 상위 2.5% 지점

print(f"\n자유도 df = {df}")
print(f"95% 신뢰구간용 t 임계값 = {t_crit:.4f}")

# 4) 신뢰구간 계산
margin = t_crit * s / np.sqrt(n)        # 오차한계 (margin of error)
ci_lower = x_bar - margin
ci_upper = x_bar + margin

print(f"\n '진짜 평균 점수(모평균)'에 대한 95% 신뢰구간:")
print(f" ({ci_lower:.2f}, {ci_upper:.2f})")

# 5) 해석 예시 출력
print("\n해석 예시:")
print(" → 이 반의 모평균은 약 95% 신뢰수준에서 "
      f"{ci_lower:.1f}점 ~ {ci_upper:.1f}점 사이에 있을 것으로 추정할 수 있습니다.")
print(" → '평균이 정확히 몇 점이다'가 아니라, '이 정도 구간 안에 있을 것이다'라고 보는 것.")


표본 크기 n = 12
표본 평균 x̄ = 73.58
표본 표준편차 s = 3.75

자유도 df = 11
95% 신뢰구간용 t 임계값 = 2.2010

 이 반의 '진짜 평균 점수(모평균)'에 대한 95% 신뢰구간:
   (71.20, 75.97)

해석 예시:
 → 이 반의 모평균은 약 95% 신뢰수준에서 71.2점 ~ 76.0점 사이에 있을 것으로 추정할 수 있습니다.
 → '평균이 정확히 몇 점이다'가 아니라, '이 정도 구간 안에 있을 것이다'라고 보는 것.


[2] 카이제곱분포(Chi-square, χ² Distribution) <hr>
- 0 이상에서 정의
- 오른쪽으로 크게 치우침
- 독립 정규분포 제곱합의 분포
- 분산(변동성)과 관련된 것들을 검정하거나, 범주형 데이터의 ‘차이/연관성’ 검정할 경우
- 예:
    * 모분산이 얼마인지 추론하고 싶을 때
    * 관측된 범주형 데이터가 기대한 비율과 맞는지 (적합도 검정)
    * 두 범주형 변수(예: 성별 vs 합격 여부)가 독립인지 (독립성 검정)
    * 여러 변수의 상관구조를 다룰 때(공분산 행렬 관련)
- 정의
    * $$ \chi^2 = Z_1^2 + Z_2^2 + \cdots + Z_k^2 \sim \chi^2_k $$


In [ ]:
## ---------------------------------------------------------------
## 성별과 제품 만족도가 독립인가?” (독립성 검정)
## - 성별과 만족도는 서로 독립이다를 검정하고 싶음
## - 설문 결과: 성별(남/여) × 만족도(만족/보통/불만족) 교차표가 있음
## ---------------------------------------------------------------
import numpy as np
from scipy import stats

# 1) 교차표 (관측도수)
#     만족  보통  불만족
# 남   30   50    20
# 여   40   45    15
obs = np.array([[30, 50, 20],
                [40, 45, 15]])

print("관측 교차표(남/여 x 만족도):")
print(obs)

# 2) 카이제곱 독립성 검정
chi2, p, dof, expected = stats.chi2_contingency(obs)

print(f"\n카이제곱 통계량 χ² = {chi2:.4f}")
print(f"자유도 df = {dof}")
print(f"p-value = {p:.4f}")

print("\n기대도수(성별과 만족이 '완전히 독립'이라고 가정했을 때의 이론적 도수):")
print(expected.round(2))

# 3) 해석
alpha = 0.05
if p < alpha:
    print("\n 유의수준 0.05에서 '성별과 만족도는 독립이다'라는 가설을 기각합니다.")
    print("   → 성별에 따라 만족도가 유의하게 다를 가능성이 큽니다.")
else:
    print("\n 유의수준 0.05에서 '성별과 만족도는 독립이다'라는 가설을 기각할 수 없습니다.")
    print("   → 성별에 따라 만족도가 다르다고 보기 어렵습니다.")


관측 교차표(남/여 x 만족도):
[[30 50 20]
 [40 45 15]]

카이제곱 통계량 χ² = 2.4060
자유도 df = 2
p-value = 0.3003

기대도수(성별과 만족이 '완전히 독립'이라고 가정했을 때의 이론적 도수):
[[35.  47.5 17.5]
 [35.  47.5 17.5]]

 유의수준 0.05에서 '성별과 만족도는 독립이다'라는 가설을 기각할 수 없습니다.
   → 성별에 따라 만족도가 다르다고 보기 어렵습니다.


[3] F-분포 (F Distribution) <hr>
- 양수만 존재
- 두 개의 분산을 비교하거나, 여러 집단 간 평균 차이를 한꺼번에 검정할 때
- 오른쪽 꼬리가 긴 형태
- 예시
    * 두 집단 이상의 평균 차이를 동시에 검정(ANOVA)
    * A반/B반/C반 평균에 차이가 있는가?
    * 회귀모형 전체가 의미 있는지 검정(F-test)
    * 두 분산(또는 여러 분산)의 차이를 검정
- 정의
    * 카이제곱(제곱합)을 자유도로 나눈 값의 비율
    * $$ F = \frac{X_1/d_1}{X_2/d_2} \sim F_{d_1, d_2} $$
    * d_1 분자: 어떤 변동(예: 집단 간 차이)
    * d_2 분모: 다른 변동(예: 집단 내 오차)
- F 값 의미
    * F 값이 크다 : 분자 쪽 변동이 분모 쪽 변동보다 상대적으로 크다

- 사용 예
    * 분산비 검정
    * ANOVA(분산분석)
    * 회귀모형 전체 검정(F-test)

In [ ]:
# 모듈 로딩 
import numpy as np
from scipy import stats

# 1) 세 반 점수 (예시 데이터)
A = np.array([75, 80, 78, 74, 77, 79, 73])
B = np.array([68, 70, 72, 71, 69, 73, 70])
C = np.array([82, 85, 84, 83, 86, 88, 81])

print("A반 평균:", A.mean())
print("B반 평균:", B.mean())
print("C반 평균:", C.mean())

# 2) 일원분산분석(ANOVA)
F_stat, p = stats.f_oneway(A, B, C)

print(f"\nF 통계량 = {F_stat:.4f}")
print(f"p-value = {p:.4f}")

# 3) 해석
alpha = 0.05
if p < alpha:
    print("\n 유의수준 0.05에서 '세 반의 평균이 모두 같다'는 가설을 기각합니다.")
    print("   → 적어도 한 반의 평균은 다른 반과 유의하게 다릅니다.")
else:
    print("\n 유의수준 0.05에서 '세 반의 평균이 모두 같다'는 가설을 기각할 수 없습니다.")
    print("   → 세 반의 평균 차이가 있다고 보기 어렵습니다.")


A반 평균: 76.57142857142857
B반 평균: 70.42857142857143
C반 평균: 84.14285714285714

F 통계량 = 63.0636
p-value = 0.0000

 유의수준 0.05에서 '세 반의 평균이 모두 같다'는 가설을 기각합니다.
   → 적어도 한 반의 평균은 다른 반과 유의하게 다릅니다.


* **t-분포**
    - 의미 : 평균 추론용
    - 적용 : 표본 적고 모분산 모를 경우
    - 활용 : t-검정, 회귀계수  
    
* **카이제곱(χ²)** 
    - 의미 : 제곱합/변동
    - 적용 : 분산 추론용
    - 활용 : 독립성검정, 적합도, 분산

* **F-분포**
    - 의미 : 변동의 비율
    - 적용 : 분산비 비교 
    - 활용 : ANOVA, 회귀 전체 검정