### [이미지 연산]
- Numpy 방식 : 관심영역 설정
    - 픽셀의 값 범위 0 ~ 255로 제한 코드 직접 작성

- 색상값 : 0 


[1] 모듈 로딩 및 데이터 준비 <hr>

In [13]:
# 모듈 로딩
import numpy as np
import cv2
import matplotlib.pyplot as plt
import koreanize_matplotlib

# 데이터 파일
FILE_NAME = '../Data/Image/flower.jpg'

In [14]:
## 데이터 로딩 및 기본 정보 출력
img = cv2.imread(FILE_NAME)
imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

print(f'로딩 Image 정보: {imgRGB.shape}') if imgRGB is not None else print("이미지 없음")

로딩 Image 정보: (321, 380, 3)


[2] 이미지 픽셀 기본 연산 <hr>

In [15]:
# ====================================================
# [2-1] 영상의 사칙 연산
# ====================================================
# 연산에 사용할 배열 생성 
a = np.uint8([[200, 50]])
b = np.uint8([[100, 100]])

# numpy 배열 직접 연산
add1 = a + b
sub1 = a - b
mult1 = a * b
div1 = a / b

# opencv api를 이용한 연산
add2 = cv2.add(a, b)
sub2 = cv2.subtract(a, b)
mult2 = cv2.multiply(a, 2)
div2 = cv2.divide(a, 3)

# 각 연산 결과 출력
print(add1, add2)
print(sub1, sub2)
print(mult1, mult2)
print(div1, div2)

[[ 44 150]] [[255 150]]
[[100 206]] [[100   0]]
[[ 32 136]] [[255 100]]
[[2.  0.5]] [[67 17]]


In [16]:
# ====================================================
# [2-2] mask와 누적 할당 연산
# ====================================================
# 연산에 사용할 배열 생성 
a = np.uint8([[1, 2]])
b = np.uint8([[10, 20]])
mask = np.array([[1, 0]], dtype=np.uint8)

# 누적 할당과의 비교 연산
c1 = cv2.add(a, b, None, mask)
print(c1)

c2 = cv2.add(a, b, b, mask)
print(c2)

[[11  0]]
[[11 20]]
