## [ Perceptron 이해 ]
- 입력 피쳐 * 가중치 -> 합계 + 절편 -> 결과
- 연산 결과를 활성화 함수(AF)를 거쳐서 최종 결과값 추출
- 뉴런의 기본 동작을 코드로 구현한 것

[1] 모듈 로딩 및 데이터 준비 <HR>

In [22]:
# [1-1] 모듈 로딩
import torch                        # 텐서 및 수치함수들 관련 모듈
import torch.nn as nn               # 인공신경망 관련 모듈
import torch.nn.functional as f     # 인공신경망 관련 함수들 모듈(AF, LF, MF ...)

# [1-2] 데이터 준비
# 랜덤 고정
torch.manual_seed(2)

## 입력 데이터 텐서 생성
xTS=torch.randint(1, 10, (3, 1))
# int텐서 -> float텐서 형변환 : tensor.type(변환타입)
xTS=xTS.type(torch.float32)

print(xTS.shape, xTS.ndim, xTS.dtype)
print(xTS)

torch.Size([3, 1]) 2 torch.float32
tensor([[1.],
        [7.],
        [9.]])


In [23]:
# 정답 텐서 생성
yTS = torch.randint(1, 10, (3, 1))
yTS = yTS.type(torch.float32)

print(yTS.shape, yTS.ndim, yTS)

torch.Size([3, 1]) 2 tensor([[1.],
        [9.],
        [4.]])


[2] 가중치와 절편 텐서 생성 <HR>

In [24]:
# 가중치와 절편 텐서 값을 랜덤값으로 초기화
# 퍼셉트론 1개 , 입력 피쳐 1개 , 샘플 3개
# 가중치와 절편 텐서 역전파로 업데이트 되어야 함 => require_grad=True
W = torch.rand(1, requires_grad=True)
b = torch.rand(1, requires_grad=True)

print(W, b)

tensor([0.4425], requires_grad=True) tensor([0.0958], requires_grad=True)


[3] 연산 --> 입력 데이터 * 가중치 + 절편 <hr>

In [25]:
output = xTS * W + b

output

tensor([[0.5383],
        [3.1935],
        [4.0786]], grad_fn=<AddBackward0>)

[4] 정답과 연산결과 값의 차이 계산 -> 손실함수 <hr>

In [26]:
# 정답
print("정답", yTS)

# 학습 결과 값
print("결과값", output)

# 정답 - 학습결과값
value = yTS-output
print("차이값", value)

# 차이값 제곱 후 평균 : Mean Square Error MSE 평균제곱오차
value = (yTS-output) ** 2
value = torch.mean(value)
print("MSE", value)

정답 tensor([[1.],
        [9.],
        [4.]])
결과값 tensor([[0.5383],
        [3.1935],
        [4.0786]], grad_fn=<AddBackward0>)
차이값 tensor([[ 0.4617],
        [ 5.8065],
        [-0.0786]], grad_fn=<SubBackward0>)
MSE tensor(11.3116, grad_fn=<MeanBackward0>)
