## [ ANN 모델 구성 ]
- 기본구성 : 입력층 - 은닉층 - 출력층
- 퍼셉트론의 가중치합계 기능처리 클래스 : Linear Layer 클래스
    - 퍼셉트론의 가중치합계 기능 처리 클래스
    - 입력값으로 피쳐 수
    - 출력값으로 출력 수 ---> 층의 퍼셉트론 개수
- nn.Module 클래스
    - 커스텀 모델 구현을 위한 부모 클래스

[1] 모듈 로딩 <hr>

In [29]:
# 텐서 및 수치함수들
import torch       

# 인공신경망 모듈           
import torch.nn as nn    
       
# 인공신경망 관련 함수들 모듈
import torch.nn.functional as F 

[2] 모델 설계 <hr>

In [30]:
# ==================================================================================
# 주제 : 거리, 신호, 날씨에 따른 도착시간 예측 모델
# 피쳐 : 거리, 신호, 날씨 3개
# 타겟 : 도착시간        1개 
# 종류 : 지도학습 + 회귀
# ==================================================================================
#               입력       퍼셉트론        출력        활성함수
# 입력층          3           10           10          Relu
#                __________________________|
#                ↓
# 은닉층          10           5            5          Relu
#                __________________________|  
#                ↓
# 출력층          5            1            1            -    (회귀는 활성함수X)
# ==================================================================================
# 클래스이름 : ANNModel
# 부모클래스 : nn.Moduel
# 오버라이딩 : __init__() : 모델 중 구성
#            forward()  : 순방향 학습
# ==================================================================================
class ANNModel(nn.Module):

    # 모델 중 구성 및 초기화 메서드
    def __init__(self):
        super().__init__()
        self.in_layer = nn.Linear(3, 10)    # 입력층
        self.hd_layer = nn.Linear(10, 5)    # 은닉층
        self.ot_layer = nn.Linear(5, 1)     # 출력층

    # 순방향 진행 메서드
    def forward(self, x):
        # 입력층 -> 가중치합계 -> AF
        out = self.in_layer(x)
        F.relu(out)

        # 은닉층 -> 가중치합계 -> AF
        out = self.hd_layer(out)
        out = F.relu(out)

        # 출력층 -> 가중치합계 Because .회귀
        out = self.ot_layer(out)
        return out

In [31]:
# 모델 인스턴스 생성
model = ANNModel()
model

ANNModel(
  (in_layer): Linear(in_features=3, out_features=10, bias=True)
  (hd_layer): Linear(in_features=10, out_features=5, bias=True)
  (ot_layer): Linear(in_features=5, out_features=1, bias=True)
)

In [32]:
# 층별로 생성된 파라미터들(w, b) 확인
for name, param in model.named_parameters():
    print(f"[{name}] ===== [{param.shape}]")
    print(f"{param}\n")

[in_layer.weight] ===== [torch.Size([10, 3])]
Parameter containing:
tensor([[ 0.5599, -0.2397, -0.0204],
        [ 0.1328, -0.0038, -0.0553],
        [-0.5109, -0.4980, -0.5195],
        [-0.5649, -0.5377, -0.4374],
        [-0.5207, -0.5416,  0.2531],
        [ 0.3541,  0.3901,  0.3110],
        [ 0.1956,  0.2543, -0.3193],
        [ 0.5198, -0.0398,  0.4981],
        [ 0.1770,  0.4519,  0.4606],
        [-0.1206, -0.1679,  0.0869]], requires_grad=True)

[in_layer.bias] ===== [torch.Size([10])]
Parameter containing:
tensor([-0.0245,  0.0903,  0.2929, -0.4511, -0.0265, -0.4531,  0.5576, -0.4061,
         0.1104, -0.1577], requires_grad=True)

[hd_layer.weight] ===== [torch.Size([5, 10])]
Parameter containing:
tensor([[ 0.1797,  0.0011, -0.0318,  0.2315,  0.2888, -0.2295, -0.3050,  0.0264,
          0.0996,  0.0722],
        [ 0.2921,  0.1419, -0.1455, -0.2166,  0.2453,  0.3031, -0.1501, -0.2024,
          0.1107, -0.2262],
        [-0.0765, -0.3128,  0.0865, -0.1078, -0.1769, -0.2011, 

In [33]:
# 임의의 데이터 : 랜덤 -> 샘플 수 5개, 피쳐 3개
torch.manual_seed(10)

feature = torch.randint(1, 10, (5, 3))
feature = feature.type(torch.float32)
feature

tensor([[6., 4., 7.],
        [5., 7., 3.],
        [9., 8., 5.],
        [4., 6., 3.],
        [2., 6., 9.]])

In [34]:
# -> 순전파 진행 : 모델변수명(텐서데이터)
model(feature)

tensor([[1.7813],
        [1.3586],
        [2.2355],
        [1.1593],
        [1.5109]], grad_fn=<AddmmBackward0>)