파일 입력과 출력
- pandas.read_XXX(): 다양한 포맷을 파일 ==> DataFrame으로 변환
    * 파일 종류에 따라서 변환 시 설정 필요함!
- pandas.to_XXX(): DataFrame ==> 다양한 포맷 str 또는 file 변환

In [1]:
import pandas as pd

In [9]:
# [1] DataFrame => CSV 변환 : pandas.to_csv()
FILE_NAME = '../02_PANDAS/Data/test_save.csv'

dataDF = pd.DataFrame([[10, 20, 30],
                       [11, 21, 31],
                       [12, 22, 32]], columns=['kor', 'eng', 'fra'])

display(dataDF)

# DataFrame ==> csv 파일로
dataDF.to_csv(FILE_NAME, index=False)

FILE_NAME = '../02_PANDAS/Data/test_save2.csv'
dataDF.to_csv(FILE_NAME, index=False, sep=' ')

kor  eng  fra
0   10   20   30
1   11   21   31
2   12   22   32

In [13]:
#_____________________________________________
# DataFrame의 다양한 형식 저장 : DF.to_OOO()
#_____________________________________________
# DF => numpy 저장
result = dataDF.to_numpy()
print(result)

# DF => string 저장
result = dataDF.to_string()
print(type(result), result, sep='\n')

[[10 20 30]
 [11 21 31]
 [12 22 32]]
<class 'str'>
   kor  eng  fra
0   10   20   30
1   11   21   31
2   12   22   32


In [20]:
# kor 컬럼 선택
korSR = dataDF['kor']
display(korSR)

# Series => numpy
print(korSR.to_numpy())

# Series => DataFrame
korDF = korSR.to_frame()
display(korDF)

0    10
1    11
2    12
Name: kor, dtype: int64

[10 11 12]


kor
0   10
1   11
2   12